"""initial schema

Revision ID: fff7e3f6c1a6
Revises: 
Create Date: 2026-03-30 11:24:03.181956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fff7e3f6c1a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('avg_rating', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_games_played', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED', name='user_status'), server_default=sa.text("'PENDING_VERIFICATION'"), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_rating >= 0 AND avg_rating <= 5', name='ck_users_avg_rating_range'),
    sa.CheckConstraint('length(btrim(full_name)) >= 2', name='ck_users_full_name_not_blank'),
    sa.CheckConstraint('total_games_played >= 0', name='ck_users_total_games_played_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> following_id', name='ck_follow_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_table('matches',
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('FOOTBALL', 'BASKETBALL', 'CRICKET', 'TENNIS', 'VOLLEYBALL', 'BADMINTON', name='sport_type'), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('facility_address', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skill_level'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'ONGOING', 'COMPLETED', 'CANCELLED', name='match_status'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes >= 10 AND duration_minutes <= 480', name='ck_matches_duration_minutes'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_matches_latitude_range'),
    sa.CheckConstraint('length(btrim(facility_address)) >= 5', name='ck_matches_facility_address_not_blank'),
    sa.CheckConstraint('length(btrim(title)) >= 3', name='ck_matches_title_not_blank'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_matches_longitude_range'),
    sa.CheckConstraint('max_players >= 2 AND max_players <= 50', name='ck_matches_max_players'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_discovery', 'matches', ['sport', 'status', 'scheduled_at'], unique=False)
    op.create_index('ix_match_location', 'matches', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_matches_host_id'), 'matches', ['host_id'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_at'), 'matches', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_skill_level'), 'matches', ['skill_level'], unique=False)
    op.create_index(op.f('ix_matches_sport'), 'matches', ['sport'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('MATCH_JOINED', 'MATCH_INVITED', 'MATCH_STATUS_CHANGED', 'NEW_FOLLOWER', 'NEW_REVIEW', 'MATCH_STARTED', 'PLAYER_REMOVED', name='notification_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_sports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sport', sa.Enum('FOOTBALL', 'BASKETBALL', 'CRICKET', 'TENNIS', 'VOLLEYBALL', 'BADMINTON', name='sport_type'), nullable=False),
    sa.Column('skill_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='skill_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sport', name='uq_user_sport')
    )
    op.create_index(op.f('ix_user_sports_user_id'), 'user_sports', ['user_id'], unique=False)
    op.create_table('match_players',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('HOST', 'PLAYER', name='match_player_role'), server_default=sa.text("'PLAYER'"), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LEFT', 'REMOVED', name='match_player_status'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'user_id')
    )
    op.create_index(op.f('ix_match_players_user_id'), 'match_players', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('length(btrim(content)) > 0', name='ck_messages_content_not_blank'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_match_sent', 'messages', ['match_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_match_id'), 'messages', ['match_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('reviews',
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('comment IS NULL OR length(btrim(comment)) <= 500', name='ck_review_comment_length'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.CheckConstraint('reviewer_id <> reviewee_id', name='ck_review_no_self_review'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_id', 'reviewee_id', 'match_id', name='uq_review_per_match')
    )
    op.create_index(op.f('ix_reviews_match_id'), 'reviews', ['match_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_match_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_match_id'), table_name='messages')
    op.drop_index('ix_message_match_sent', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_match_players_user_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_user_sports_user_id'), table_name='user_sports')
    op.drop_table('user_sports')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notification_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_sport'), table_name='matches')
    op.drop_index(op.f('ix_matches_skill_level'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_host_id'), table_name='matches')
    op.drop_index('ix_match_location', table_name='matches')
    op.drop_index('ix_match_discovery', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_table('users')
    op.execute("DROP TYPE notification_type")
    op.execute("DROP TYPE match_player_status")
    op.execute("DROP TYPE match_player_role")
    op.execute("DROP TYPE match_status")
    op.execute("DROP TYPE skill_level")
    op.execute("DROP TYPE sport_type")
    op.execute("DROP TYPE user_status")
    # ### end Alembic commands ###
